phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo intall
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo post_build

